export enum SyncModelType {
    country = 'country',
    province = 'province',
    city = 'city',
    port = 'port',
    company = 'company',
    branch = 'branch',
    unit = 'unit',
    bank = 'bank',
    currency = 'currency',
    group = 'group',
    groupToModule = 'groupToModule',
    groupService = 'groupService',
    service = 'service',
    vesselType = 'vesselType',
    vesselTitle = 'vesselTitle',
    conversionSize = 'conversionSize',
    employee = 'employee',
    user = 'user',
    serviceToActivity = 'serviceToActivity',
    configuration = 'configuration',
    activity = 'activity',
}